# Generated by Django 5.0.4 on 2024-04-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theblog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="title_tag",
            field=models.CharField(default="Mój Blog", max_length=255),
        ),
    ]
