# Generated by Django 5.0.4 on 2024-05-21 09:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theblog", "0004_category_post_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                related_name="blog_post", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
